stages:
- build
- test
- run

# Using 3.6 as it's the minimal required version
image: python:3.7.2

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

build:
  stage: build
  script:
    - apt-get update -y
    - apt-get install default-jre -y
    # TODO -> Have the jar url in a env/config variable somewhere to use it in the Makefile as well
    - wget https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/5.2.0-SNAPSHOT/openapi-generator-cli-5.2.0-20210629.131254-142.jar -O openapi-generator-cli.jar
    - make > /dev/null
    - git config --global user.name "Mr.Roboto 🤖"
    - git config --global user.email "mrRoboto@blockdaemon.com"
    - git add ./ubiquity ./docs
    - git commit -m "UB-00 Updating generated code with changes from ${CI_JOB_ID}"
    - git push http://gitlab-ci-token:${AUTH_TOKEN_UBIQUITY_PYTHON_CLIENT}@gitlab.com/Blockdaemon/ubiquity/ubiquity-python-client.git HEAD:master
  only:
      refs:
        - master
      changes:
        - spec/openapi.yaml


test:
  stage: test
  script:
    - pip install -r test-requirements.txt
    - make test

run:
  stage: run
  script:
    - python setup.py bdist_wheel
    # an alternative approach is to install and run:
    - pip install dist/*
    # run the command here
  artifacts:
    paths:
      - dist/*.whl
