# flake8: noqa

"""
    Ubiquity REST API

    Ubiquity provides a RESTful and uniform way to access blockchain resources, with a rich and reusable model across multiple cryptocurrencies.  [Documentation](https://app.blockdaemon.com/docs/ubiquity)  ### Protocols #### Mainnet The following protocols are currently supported: * bitcoin * ethereum * polkadot * xrp * algorand * stellar * dogecoin  #### Testnet * bitcoin/testnet * ethereum/ropsten * dogecoin/testnet  ##### Pagination Certain resources contain a lot of data, more than what's practical to return for a single request. With the help of pagination, the data is split across multiple responses. Each response returns a subset of the items requested and a continuation token.  To get the next batch of items, copy the returned continuation token to the continuation query parameter and repeat the request with the new URL. In case no continuation token is returned, there is no more data available.   # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: support@blockdaemon.com
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from ubiquity.ubiquity_openapi_client.api_client import ApiClient

# import Configuration
from ubiquity.ubiquity_openapi_client.configuration import Configuration

# import exceptions
from ubiquity.ubiquity_openapi_client.exceptions import OpenApiException
from ubiquity.ubiquity_openapi_client.exceptions import ApiAttributeError
from ubiquity.ubiquity_openapi_client.exceptions import ApiTypeError
from ubiquity.ubiquity_openapi_client.exceptions import ApiValueError
from ubiquity.ubiquity_openapi_client.exceptions import ApiKeyError
from ubiquity.ubiquity_openapi_client.exceptions import ApiException
